### PR TITLE
NXP-11250 - ActivityStreamService produces Activity events

### PR DESCRIPTION
**Pull request by nelsonsilva**
Added activityCreated, activityRemoved, activityReplyCreated and activityReplyRemoved events.

### CODE REVIEW

**Comment by nelsonsilva** [comment]
@troger Did you get a chance to look at this?

**Comment by troger** [comment]
Hi Nelson,

Thanks for you PR!

I'm not convinced we can merge this PR as it. Here is why:

The idea was that the `ActivityStreamFilter` should handle the creation of an `Activity` and also the query.
Moreover, as adding an `Activity` through `ActivityStreamService#addActivity` is synchronous, we need to do it quicky

For now, most of the `ActivityStreamFilter`s do nothing more when an `Activity` is created but they will be able to store related activities in another table, or do anything else that can improve performances.
When querying activities through the filter, it knows where it has stored everything. So the point is to have everything related to creation / deletion / query of an `Activity` in the same `ActivityStreamFilter` class.

Another thing is that when we add activities, we rely on an `EntityManager` which is stored in a `ThreadLocal` on the `ActivityStreamService`: that means we need to be in the same thread. That's not always possible using the `EventListener`s as we cannot force people to use only synchronous `EventListener`s when handling activities.

However, sending events when an `Activity` is created / deleted is still a good thing that's missing in the default API so that users can plug their own code to do anything non-related to storing activities through the `EntityManager`.
The main issue with having a custom `ActivityContext` is that we won't get one from a `ReconnectedEventBundle` (in any async events) as it will create only standard `EventContext` or `DocumentEventContext`.

**Comment by nelsonsilva** [comment]
@troger Ok. I understand the limitations. I'm mainly interested in the activity created / deleted events so If you feel we should keep the filters I'm all for it. You'll just need to update the docs to make it clear why there are filters and events since the two seem to overlap.

**Comment by atchertchian** [comment]
should we forget about this PR please? :)

**Comment by nelsonsilva** [comment]
😢

**Pull request closed without merging**
